# Travis-CI Build for libgit2
# see travis-ci.org for details

language: c

compiler:
  - gcc
  - clang

# Settings to try
env:
  - OPTIONS="-DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release"
  - OPTIONS="-DBUILD_CLAR=ON -DBUILD_EXAMPLES=ON"

matrix:
 include:
   - compiler: i586-mingw32msvc-gcc
     env: OPTIONS="-DBUILD_CLAR=OFF -DWIN32=ON -DMINGW=ON"

install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install libssh2-1-dev

# Run the Build script and tests. At the end, re-run the push tests over ssh as well.
script:
 - sudo start ssh
 - mkdir $HOME/_temp
 - git init --bare $HOME/_temp/test.git
 - git daemon --listen=localhost --export-all --enable=receive-pack --base-path=$HOME/_temp $HOME/_temp 2>/dev/null &
 - export GITTEST_REMOTE_URL="git://localhost/test.git"
 - mkdir _build
 - cd _build
 - cmake .. -DCMAKE_INSTALL_PREFIX=../_install $OPTIONS
 - cmake --build . --target install
 - ctest -V .
 - killall git-daemon
 - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
 - cat ~/.ssh/id_rsa.pub >>~/.ssh/authorized_keys
 - ssh-keyscan -t rsa localhost >>~/.ssh/known_hosts
 - export GITTEST_REMOTE_URL="ssh://$USER@localhost/$HOME/_temp/test.git"
 - export GITTEST_REMOTE_SSH_KEY="$HOME/.ssh/id_rsa"
 - export GITTEST_REMOTE_SSH_PUBKEY="$HOME/.ssh/id_rsa.pub"
 - export GITTEST_REMOTE_SSH_PASSPHRASE=""
 - ./libgit2_clar -sonline::push
 - exit $?

# Run Tests
after_success:
 - sudo apt-get -qq install valgrind
 - valgrind --leak-check=full --show-reachable=yes --suppressions=../libgit2_clar.supp ./libgit2_clar -ionline

# Only watch the development branch
branches:
 only:
   - development
