# Travis-CI Build for libgit2
# see travis-ci.org for details

language: c

compiler:
  - gcc
  - clang

# Settings to try
env:
  - OPTIONS="-DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release"
  - OPTIONS="-DBUILD_CLAR=ON -DBUILD_EXAMPLES=ON"

matrix:
 include:
   - compiler: i586-mingw32msvc-gcc
     env: OPTIONS="-DBUILD_CLAR=OFF -DWIN32=ON -DMINGW=ON"

install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install libssh2-1-dev

# Run the Build script and tests. At the end, re-run the push tests over ssh as well.
script:
 - script/travis.sh

# Run Tests
after_success:
 - sudo apt-get -qq install valgrind
 - valgrind --leak-check=full --show-reachable=yes --suppressions=../libgit2_clar.supp ./libgit2_clar -ionline

# Only watch the development branch
branches:
 only:
   - development
